apiVersion: v1
kind: Service
metadata:
  name: couchbase-metrics
  namespace: default 
  labels:
    app: couchbase
spec:
  ports:
  - name: metrics
    port: 9091 
    protocol: TCP
  selector:
    app: couchbase
