prometheus:
  prometheusSpec:
    additionalServiceMonitors:
      - name: couchbase
        additionalLabels:
          - app: couchbase
        endpoints:
          - port: metrics
            interval: 5s
        selector:
          matchLabels:
            app: couchbase
