apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couchbase
  labels:
    app: couchbase
    release: prometheus
spec:
  endpoints:
  - port: metrics
    interval: 5s
  selector:
    matchLabels:
      app: couchbase
